name: FE Base Branch Coverage
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run FE tests with coverage
    runs-on: ubuntu-latest
    steps:
      - name: checkout actions
        uses: actions/checkout@v3

      - name: set node to 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: set npm to 6
        run: npm i -g npm@6

      - name: install dependencies
        working-directory: ./UI/QueryBuilder
        run: npm ci

      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1

      - name: run tests
        working-directory: ./UI/QueryBuilder
        run: npm run test:ci -- --maxWorkers=${{ steps.cpu-cores.outputs.count }}

      - name: Save code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./UI/QueryBuilder/coverage/report.json
